version: '3'
services:
  hosted: 
    container_name: hosted
    build:
      context: ./
      dockerfile: ./docker/hosted.Dockerfile
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
        - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    build: ./tools/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    build: ./tools/mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    build: ./tools/redis/
    ports:
      - "6379:6379"

  insight:
    container_name: insight
    build: ./tools/insight/
    ports:
      - "8001:8001"